// Generated by CoffeeScript 1.9.3
(function() {
  var angieApp;

  angieApp = angular.module('angieApp');

  angieApp.controller('categoryCtrl', function($scope, $products, $routeParams, $location, $anchorScroll, $translate) {
    $scope.products = $products;
    $scope.lang = $translate.use();
    $products.get();
    $scope.$on("productChange", function() {
      return $scope.products = $products;
    });
    $scope.goto = function(tab) {
      $location.path("/");
      return $location.hash(tab);
    };
    $scope.selectedTag = $routeParams.name;
    $scope.changeLang = function(lang) {
      $translate.use(lang);
      return $scope.lang = $translate.use();
    };
    return $scope.filterTag = function(product) {
      var el, i, len, ref, tag;
      el = false;
      ref = product.tags;
      for (i = 0, len = ref.length; i < len; i++) {
        tag = ref[i];
        if (tag === $routeParams.name) {
          console.log(product.name);
          el = true;
        }
      }
      return el;
    };
  });

}).call(this);
