// Generated by CoffeeScript 1.9.3
(function() {
  var angieApp;

  angieApp = angular.module('angieApp');

  angieApp.factory('$products', function($http, $location, $rootScope) {
    var $products;
    return $products = {
      list: [],
      all: [],
      product: {},
      tags: [],
      get: function(callback, name) {
        return $http.get('/products/products.json').success(function(response) {
          $products.list = response.products;
          $products.all = response.products.mobile.concat(response.products.web);
          $products.tags = response.tags;
          if (callback != null) {
            return callback(name);
          }
        });
      },
      getProduct: function(name) {
        var i, j, len, len1, product, ref, ref1, ref2;
        ref = $products.list.mobile;
        for (i = 0, len = ref.length; i < len; i++) {
          product = ref[i];
          if (product.name.toLowerCase() === name) {
            $products.product = product;
            $products.product.type = "mobile";
            $products.changed();
          }
        }
        ref1 = $products.list.web;
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          product = ref1[j];
          if (product.name.toLowerCase() === name) {
            $products.product = product;
            $products.product.type = "web";
            $products.changed();
          }
        }
        if (((ref2 = $products.product) != null ? ref2.name : void 0) == null) {
          return $location.path("/");
        }
      },
      changed: function() {
        return $rootScope.$broadcast("productChange");
      }
    };
  });

}).call(this);
