// Generated by CoffeeScript 1.9.3
(function() {
  var angieApp;

  angieApp = angular.module('angieApp', ['ngRoute', 'duScroll', 'pascalprecht.translate']).config(($locationProvider)-> {
      $locationProvider.html5Mode(true);
    });;

}).call(this);
