// Generated by CoffeeScript 1.9.3
(function() {
  var angieApp;

  angieApp = angular.module('angieApp');

  angieApp.controller('productCtrl', function($scope, $products, $routeParams, $location, $anchorScroll, $translate) {
    $scope.products = $products;
    $scope.lang = $translate.use();
    if ($products.list.mobile != null) {
      $products.getProduct($routeParams.name);
    } else {
      $products.get($products.getProduct, $routeParams.name);
    }
    $scope.$on("productChange", function() {
      return $scope.products = $products;
    });
    $scope.goto = function(tab) {
      $location.path("/");
      return $location.hash(tab);
    };
    return $scope.changeLang = function(lang) {
      $translate.use(lang);
      return $scope.lang = $translate.use();
    };
  });

}).call(this);
